# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playername', models.CharField(max_length=30)),
                ('goal_name', models.CharField(max_length=400)),
                ('current_name', models.CharField(max_length=400)),
                ('won', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WikiPathStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_path', models.IntegerField()),
                ('page_name', models.CharField(max_length=500)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiapp.WikiGame')),
            ],
        ),
    ]
